const clothes_list = [
    {
        url: './models/female_objs/blue_jeans/',
        obj: 'Blue_Jeans.obj',
        mtl: 'Blue_Jeans.mtl',
        type: 'trousers',
        title: 'Skinny jeans',
        createBy: 'Create by Lookfit',
        style: ['Mid Waist', 'Casual'],
        cloth: ['Cotton'],
        size: ['XS', 'S', 'M', 'L', 'XL'],
        brand: 'Lookfit',
        color: ['Blue', 'Grey'], //'#546E7A'
    },
    {
        url: './models/female_objs/dark_blue_jeans/',
        obj: 'dark_blue_jeans.obj',
        mtl: 'dark_blue_jeans.mtl',
        type: 'trousers',
        title: 'High waist jeans',
        createBy: 'Create by Lookfit',
        style: ['High Waist', 'Preppy'],
        cloth: ['Cotton', 'Poliester'],
        size: ['XS', 'S', 'M', 'L', 'XL'],
        brand: 'Lookfit',
        color: ['Blue'],
    },
    {
        url: './models/female_objs/shorts/',
        obj: 'shortik.obj',
        mtl: 'shortik.mtl',
        type: 'shorts',
        title: 'Ripped denim shorts',
        createBy: 'Create by Lookfit',
        style: ['High Waist', 'Casual', 'Ripped'],
        cloth: ['Cotton'],
        size: ['XS', 'S', 'M', 'L', 'XL'],
        brand: 'Lookfit',
        color: ['Blue', 'white'],
    },
    {
        url: './models/female_objs/dress/',
        obj: 'dress.obj',
        mtl: 'dress.mtl',
        type: 'dress',
        title: 'Vintage dress',
        createBy: 'Create by Lookfit',
        style: ['elegant', 'laces', 'tight-fitting'],
        cloth: ['Lana'],
        size: ['XS', 'S', 'M', 'L', 'XL'],
        brand: 'Lookfit',
        color: ['pink', 'red'], // EF9A9A
    },
    {
        url: './models/female_objs/jacket_blue/',
        obj: 'jacket_blue.obj',
        mtl: 'jacket_blue.mtl',
        type: 'jacket',
        title: 'Denim jacket',
        createBy: 'Create by Lookfit',
        style: ['Casual'],
        cloth: ['Cotton'],
        size: ['XS', 'S', 'M', 'L', 'XL'],
        brand: 'Lookfit',
        color: ['Blue'],
    },
    {
        url: './models/female_objs/jacket_black/',
        obj: 'jacket_black.obj',
        mtl: 'jacket_black.mtl',
        type: 'jacket',
        title: 'Biker jacket',
        createBy: 'Create by Lookfit',
        style: ['elegant', 'tight-fitting'],
        cloth: ['Leather'],
        size: ['XS', 'S', 'M', 'L', 'XL'],
        brand: 'Lookfit',
        color: ['black'],
    },

    {
        url: './models/female_objs/blue_jeans/',
        obj: 'Blue_Jeans.obj',
        mtl: 'Blue_Jeans.mtl',
        type: 'trousers',
        title: 'Skinny jeans',
        createBy: 'Create by Lookfit',
        style: ['Mid Waist', 'Casual'],
        cloth: ['Cotton'],
        size: ['XS', 'S', 'M', 'L', 'XL'],
        brand: 'Lookfit',
        color: ['Blue', 'Grey'], //'#546E7A'
    },
    {
        url: './models/female_objs/dark_blue_jeans/',
        obj: 'dark_blue_jeans.obj',
        mtl: 'dark_blue_jeans.mtl',
        type: 'trousers',
        title: 'High waist jeans',
        createBy: 'Create by Lookfit',
        style: ['High Waist', 'Preppy'],
        cloth: ['Cotton', 'Poliester'],
        size: ['XS', 'S', 'M', 'L', 'XL'],
        brand: 'Lookfit',
        color: ['Blue'],
    },
    {
        url: './models/female_objs/shorts/',
        obj: 'shortik.obj',
        mtl: 'shortik.mtl',
        type: 'shorts',
        title: 'Ripped denim shorts',
        createBy: 'Create by Lookfit',
        style: ['High Waist', 'Casual', 'Ripped'],
        cloth: ['Cotton'],
        size: ['XS', 'S', 'M', 'L', 'XL'],
        brand: 'Lookfit',
        color: ['Blue', 'white'],
    },
    {
        url: './models/female_objs/dress/',
        obj: 'dress.obj',
        mtl: 'dress.mtl',
        type: 'dress',
        title: 'Vintage dress',
        createBy: 'Create by Lookfit',
        style: ['elegant', 'laces', 'tight-fitting'],
        cloth: ['Lana'],
        size: ['XS', 'S', 'M', 'L', 'XL'],
        brand: 'Lookfit',
        color: ['pink', 'red'], // EF9A9A
    },
    {
        url: './models/female_objs/jacket_blue/',
        obj: 'jacket_blue.obj',
        mtl: 'jacket_blue.mtl',
        type: 'jacket',
        title: 'Denim jacket',
        createBy: 'Create by Lookfit',
        style: ['Casual'],
        cloth: ['Cotton'],
        size: ['XS', 'S', 'M', 'L', 'XL'],
        brand: 'Lookfit',
        color: ['Blue'],
    },
    {
        url: './models/female_objs/jacket_black/',
        obj: 'jacket_black.obj',
        mtl: 'jacket_black.mtl',
        type: 'jacket',
        title: 'Biker jacket',
        createBy: 'Create by Lookfit',
        style: ['elegant', 'tight-fitting'],
        cloth: ['Leather'],
        size: ['XS', 'S', 'M', 'L', 'XL'],
        brand: 'Lookfit',
        color: ['black'],
    },
];