const clothes_list = [
    {
        url: './models/female_objs/blue_jeans/',
        obj: 'Blue_Jeans.obj',
        mtl: 'Blue_Jeans.mtl',
        type: 'trousers',
        title: 'Skinny jeans',
        visible: false,
        dressingType: 'bottom',
    },
    {
        url: './models/female_objs/dark_blue_jeans/',
        obj: 'dark_blue_jeans.obj',
        mtl: 'dark_blue_jeans.mtl',
        type: 'trousers',
        title: 'Skinny jeans',
        visible: false,
    },
    {
        url: './models/female_objs/shorts/',
        obj: 'shortik.obj',
        mtl: 'shortik.mtl',
        type: 'shorts',
        title: 'Ripped denim shorts',
        visible: false,
    },
    {
        url: './models/female_objs/dress/',
        obj: 'dress.obj',
        mtl: 'dress.mtl',
        type: 'dress',
        title:'Vintage dress',
        visible: false,
    },
    {
        url: './models/female_objs/jacket_blue/',
        obj: 'jacket_blue.obj',
        mtl: 'jacket_blue.mtl',
        type: 'jacket',
        title: 'Jeans jacket',
        visible: false,
    },
    {
        url: './models/female_objs/jacket_black/',
        obj: 'jacket_black.obj',
        mtl: 'jacket_black.mtl',
        type: 'jacket',
        title: 'Biker jacket',
        visible: false,
    },

    {
        url: './models/female_objs/blue_jeans/',
        obj: 'Blue_Jeans.obj',
        mtl: 'Blue_Jeans.mtl',
        type: 'trousers',
        title: 'Skinny jeans',
        visible: false,
        dressingType: 'bottom',
    },
    {
        url: './models/female_objs/dark_blue_jeans/',
        obj: 'dark_blue_jeans.obj',
        mtl: 'dark_blue_jeans.mtl',
        type: 'trousers',
        title: 'Skinny jeans',
        visible: false,
    },
    {
        url: './models/female_objs/shorts/',
        obj: 'shortik.obj',
        mtl: 'shortik.mtl',
        type: 'shorts',
        title: 'Ripped denim shorts',
        visible: false,
    },
    {
        url: './models/female_objs/dress/',
        obj: 'dress.obj',
        mtl: 'dress.mtl',
        type: 'dress',
        title:'Vintage dress',
        visible: false,
    },
    {
        url: './models/female_objs/jacket_blue/',
        obj: 'jacket_blue.obj',
        mtl: 'jacket_blue.mtl',
        type: 'jacket',
        title: 'Jeans jacket',
        visible: false,
    },
    {
        url: './models/female_objs/jacket_black/',
        obj: 'jacket_black.obj',
        mtl: 'jacket_black.mtl',
        type: 'jacket',
        title: 'Biker jacket',
        visible: false,
    },
];